### ISSUE TITLE
Multiple demo workflows give error `ValueError: cannot reshape array of size 7 into shape (1,)`

### ISSUE THREAD

**Issue by gcapes** [hpcflow/matflow-new#316]
Affected demo workflows:
- [x] #297 
- [x] #312 
- [ ] #292 
- [x] #296 
- [ ] #299 
- [ ] #310 
- [x] #312

**Comment by gcapes** [comment]
@dkfellows 
Do you have any idea where this error is coming from?

**Comment by JQFonseca** [comment]
@aplowman I understand you are busy, but could you maybe point us to the source of this? We can do the legwork, but it appears to be something about the workflow file structure. Did we use to have a similar issue with the hdf5 file?

**Comment by aplowman** [comment]
I can't reproduce this locally or on the cluster I have access to. @gcapes do you get the same result locally? And can you share the ouput from `pip list`?

**Comment by gcapes** [comment]
Yep I get the same locally. I've just seen that there was a new release last week - I'll try that next as I was using 0.3.0a138....
Well it turns out I can't install the a139 version
```
pip install matflow-new==0.3.0a139
ERROR: Could not find a version that satisfies the requirement matflow-new==0.3.0a139 (from versions: 0.3.0a13, 0.3.0a14, 0.3.0a15, 0.3.0a17, 0.3.0a18, 0.3.0a19, 0.3.0a20, 0.3.0a21, 0.3.0a22, 0.3.0a23, 0.3.0a24, 0.3.0a25, 0.3.0a26, 0.3.0a27, 0.3.0a28, 0.3.0a29, 0.3.0a30, 0.3.0a31, 0.3.0a32, 0.3.0a33, 0.3.0a34, 0.3.0a35, 0.3.0a36, 0.3.0a37, 0.3.0a38, 0.3.0a39, 0.3.0a40, 0.3.0a41, 0.3.0a42, 0.3.0a43, 0.3.0a44, 0.3.0a45, 0.3.0a46, 0.3.0a47, 0.3.0a48, 0.3.0a49, 0.3.0a51, 0.3.0a52, 0.3.0a53, 0.3.0a54, 0.3.0a55, 0.3.0a56, 0.3.0a57, 0.3.0a58, 0.3.0a59, 0.3.0a60, 0.3.0a61, 0.3.0a62, 0.3.0a63, 0.3.0a64, 0.3.0a65, 0.3.0a66, 0.3.0a67, 0.3.0a68, 0.3.0a69, 0.3.0a70, 0.3.0a71, 0.3.0a72, 0.3.0a73, 0.3.0a74, 0.3.0a75, 0.3.0a76, 0.3.0a77, 0.3.0a78, 0.3.0a79, 0.3.0a80, 0.3.0a81, 0.3.0a82, 0.3.0a83, 0.3.0a84, 0.3.0a85, 0.3.0a86, 0.3.0a87, 0.3.0a89, 0.3.0a90, 0.3.0a91, 0.3.0a92, 0.3.0a93, 0.3.0a94, 0.3.0a95, 0.3.0a96, 0.3.0a97, 0.3.0a98, 0.3.0a99, 0.3.0a100, 0.3.0a101, 0.3.0a102, 0.3.0a103, 0.3.0a106, 0.3.0a107, 0.3.0a109, 0.3.0a110, 0.3.0a111, 0.3.0a112, 0.3.0a113, 0.3.0a114, 0.3.0a115, 0.3.0a116, 0.3.0a117, 0.3.0a118, 0.3.0a119, 0.3.0a120, 0.3.0a121, 0.3.0a122, 0.3.0a123, 0.3.0a124, 0.3.0a125, 0.3.0a126, 0.3.0a128, 0.3.0a129, 0.3.0a130, 0.3.0a131, 0.3.0a132, 0.3.0a133, 0.3.0a134, 0.3.0a135, 0.3.0a136, 0.3.0a137, 0.3.0a138)
ERROR: No matching distribution found for matflow-new==0.3.0a139
```

`pip list` gives
```
Package            Version
------------------ -----------
aiohappyeyeballs   2.4.4
aiohttp            3.11.11
aiosignal          1.3.2
asciitree          0.3.3
attrs              25.1.0
bcrypt             4.2.1
certifi            2024.12.14
cffi               1.17.1
charset-normalizer 3.4.1
click              8.1.8
colorama           0.4.6
contourpy          1.3.1
cryptography       44.0.0
cycler             0.12.1
damask             3.0.1
damask-parse       0.2.30
Deprecated         1.2.18
fasteners          0.19
fonttools          4.55.6
frozenlist         1.5.0
fsspec             2022.11.0
h5py               3.12.1
hpcflow-new2       0.2.0a189
idna               3.10
kiwisolver         1.4.8
markdown-it-py     3.0.0
matflow-new        0.3.0a138
matplotlib         3.10.0
mdurl              0.1.2
msgpack            1.1.0
multidict          6.1.0
numcodecs          0.15.0
numpy              1.26.4
packaging          24.2
pandas             2.2.3
paramiko           3.5.0
pillow             11.1.0
pip                24.0
platformdirs       4.3.6
propcache          0.2.1
psutil             5.9.8
pycparser          2.22
Pygments           2.19.1
PyNaCl             1.5.0
pyparsing          3.2.1
python-dateutil    2.9.0.post0
pytz               2024.2
PyYAML             6.0.2
requests           2.32.3
reretry            0.11.8
rich               13.9.4
ruamel.yaml        0.18.10
ruamel.yaml.clib   0.2.12
scipy              1.15.1
setuptools         65.5.0
six                1.17.0
termcolor          1.1.0
typing_extensions  4.12.2
tzdata             2025.1
urllib3            2.3.0
valida             0.7.5
vtk                9.4.1
watchdog           2.3.1
wrapt              1.17.2
yarl               1.18.3
zarr               2.18.4
```

**Comment by aplowman** [comment]
This should fix it: https://github.com/hpcflow/hpcflow-new/pull/737

**Comment by gcapes** [comment]
@dkfellows 
This has been merged, but there has been no release yet, so it's not really fixed from a user perspective. Could you please take a look at the GH actions release workflow?

**Comment by dkfellows** [comment]
The blocking problem with releases seems done now (according to hpcflow/hpcflow-new#738). Closing.
